name: CI

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
        
      - name: Build with Ant
        run: ant -f build-auto.xml dist
        
      - name: Move builds to apporiate artifact folders
        run: |
          # Remove all unnecessary build folders since we will only release builds with archived with 7zip
          cd dist
          rm -R -- */
          cd ..
          # Make directories for artifact releases and move all of builds to their respective folders
          mkdir -p dist/{buildWin32,buildLinux,buildMacOS}
          mv dist/*windows* dist/buildWin32/
          mv dist/*linux* dist/buildLinux/
          mv dist/*macosx* dist/buildMacOS/      
      - name: Publishing Win32 builds
        uses: actions/upload-artifact@v2
        with:
          name: Win32 builds
          path: dist/buildWin32
      
      - name: Publishing Linux builds
        uses: actions/upload-artifact@v2
        with:
          name: Linux builds
          path: dist/buildLinux

      - name: Publishing MacOS builds
        uses: actions/upload-artifact@v2
        with:
          name: Mac OS builds
          path: dist/buildMacOS
          
      - name: Release tagged builds
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            dist/buildLinux/*.7z
            dist/buildMacOS/*.7z
            dist/buildWin32/*.7z
